### ISSUE TITLE
Publishing multiple messages throws errors when formats are different

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/eftl#1]
Hopefully simple example to show what's happening:

in a hacked version of the publish.go code in the examples directory .... i've added a second msg to be sent. The messages differ as one of the fields in the first message is a string and a double in the second.
The code creates two eftl.Message objects ... and then publishes them. The second publish fails with:

publish failed: 11: Invalid type argument 'string', should be 'double'

Why ? The second message is completely independant of the first just being sent to the same destination ...

Code snippet:
`
	msg := eftl.Message{"_dest": "FlightData",
		"hex": "335BC", "flight": "KZR941",
		"lat": 51.131516, "lon": "-0.031771",
		"altitude": "4225", "track": "236",
		"speed": "148", "messages": "76",
	}

	// Publish the message.
	err = conn.Publish(msg)
	if err != nil {
		log.Println("publish failed:", err)
	}

	log.Println("published message:", msg)

	msg2 := eftl.Message{"_dest": "FlightData",
		"hex": "335BC", "flight": "KZR941",
		"lat": "51.131516", "lon": "-0.031771",
		"altitude": "4225", "track": "236",
		"speed": "148", "messages": "76",
	}

	// Publish the message.
	err = conn.Publish(msg2)
	if err != nil {
		log.Println("publish failed:", err)
	}

	log.Println("published message:", msg2)
}`

**Comment by bpetersen-tibco** [comment]
This issue was introduced in eFTL 3.3.0 and has since been fixed in eFTL 3.4.0. The issue only involved the 3.3.0 eFTL server executable and not the eFTL clients.

**Comment by tibcodenny** [comment]
Addressed with eFTL 3.4.0
